language: csharp
mono: none
dotnet: 2.2
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: true
os:
  - linux
  - osx
osx_image: xcode8.3
before_script:
  - chmod +x ./build.sh
script:
  - ./build.sh